# -*- coding: utf-8 -*-
"""QualquerCoisaEli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bYFLFOAXgE3TCzZoecVyr0zKg7x3NGne
"""

# Palíndrome

Palind = ["arara", "casa", "rodador", "socos", "moises" ]
PalRes = [ True, False, True, True, False ]

# Abrir o Palindrome