# -*- coding: utf-8 -*-
"""QualquerCoisaEli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bYFLFOAXgE3TCzZoecVyr0zKg7x3NGne
"""

# Palíndrome

Palind = ["arara", "casa", "rodador", "socos", "moises" , "Muoi"]
PalRes = [ 0,0,0,0,0,0 ]
Palres = [ True, False, True, True, False, False]

# Códiogo do Moises
for a in range (len(Palind)):
  RPal = (Palind[a] [::-1])
  if (RPal == Palind[a]):
    PalRes[a] = True

  else: 
    PalRes[a] = False
    
print (PalRes)

if (PalRes==Palres):
  print ("Certou Miserávi")
else: 
  print ("Erooooouuu")

"""# Queridos Formadores,
## Parabéns pelo excelentíssimo curso.


Minhas críticas são mais incentivos para continuar essa longa jornada na vida docente. Sendo elas, listadas abaixo:


*   Procurem colocar mais imagens para dar um maior dinamismo na aula
*   Os conceitos podem ser feitos de forma breve e preferencialmente comentando as diferenças entre os comandos.
*   Para facilitar alguns trabalhos e ganhar tempo em formação, dêem preferência a prints do código, para evitar problemas como "travado em 39%"
*   Por fim, como todo bom curso de programação ou relacionado, sempre comece o passo-a-passo com a mão na massa, com a intrução mais básica... O clássico : "Hello World"

ObsFinal: Jefferson, minsina React
"""