# -*- coding: utf-8 -*-
"""Rsaads.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17H8TCTBKuHFzjft1HxpB0zY87lH1H_PN
"""

#python 3 hackton

lista = ["arara","ama","ele","osso","radar","biscoito","homem","bolacha","bonoro"]
lista2 = [True,True,True,True,True,False,False,False,False]